### ISSUE TITLE
请问如何登陆，没法登陆进去看效果，可以解答一下吗

### ISSUE THREAD

**Issue by gesha96** [emacle/vue-php-admin-V3#1]
接口报错提示：errError: timeout of 5000ms exceeded

**Comment by emacle** [comment]
demo 地址已经不能使用了，需要自己搭建前后端代码 看README里的使用说明，

**Comment by gesha96** [comment]
好的，感谢！




------------------ 原始邮件 ------------------
发件人: "emacle"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 中午11:43
收件人: "emacle/vue-php-admin-V3"<vue-php-admin-V3@noreply.github.com>;
抄送: "じLisa"<690941858@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [emacle/vue-php-admin-V3] 请问如何登陆，没法登陆进去看效果，可以解答一下吗 (#1)




demo 地址已经不能使用了，需要自己搭建前后端代码 看README里的使用说明，
